# Generated by Django 4.1.7 on 2023-03-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='getuserinfo',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
