# Generated by Django 4.1.7 on 2023-04-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nav_app', '0002_getuserinfo_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GetUserInfo',
            new_name='RideRequest',
        ),
        migrations.AlterModelTable(
            name='riderequest',
            table='RideRequest',
        ),
    ]
